<?php 


error_reporting(0);

session_start();


?>


<!DOCTYPE php>
<php>

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title></title>
	<link rel="stylesheet" type="text/css" href="donprcs.css">
	<div style="background-image:url('https://htmlcolorcodes.com/assets/images/html-color-codes-color-tutorials-hero.jpg'); height:250px;"><br><br><br><br><br><center><font color="white" size="20px">DONOR ELIGIBILITY</font></center></div><br><br><br><br><br>
</head>
<body>
	<center><button class="button button1" onclick="document.location='donprcs.php'">Where can one donate blood?</a></button>
	<button class="button button1" onclick="document.location='postdon.php'">Post-Donation</button>
	<button class="button button1"onclick="document.location='blddnt.php'">What happens to the Blood you donated?</button>
	</center>

	<h2>Screening</h2>
Blood safety means ensuring that it is safe for the donor to donate blood given current health status as well as that donated blood carries minimal risk of adverse effects for the recipient in terms of matching blood groups and is free of Transfusion Transmissible Infections (TTIs). TTIs are infections which occur in a recipient of a blood transfusion if the transfused blood contains a pathogen. Many organisms like bacteria, viruses and parasites can be transmitted through blood transfusions.

The Drugs and Cosmetics Act of India mandates that all blood units that are collected in blood banks for the purpose of transfusion should be screened for the following organisms:

 <ul><li>Human Immunodeficiency Virus (HIV)</li>

 <li>Hepatitis B and Hepatitis C Virus</li>

 <li>Treponema Pallidum (which causes Syphilis)</li>

<li> Plasmodium species (which causes Malaria)</li></ul>

Blood which is detected as having any of these infections is destroyed to prevent infecting others.
<h2>Separation</h2>
<img src="http://nbtc.naco.gov.in/images/seperation.png"><br>
Blood is often separated into its individual components, so patients can be given what they need, for example red blood cells or platelets.<br><br>

<strong>Red Blood Cells (RBCs)</strong> contain haemoglobin, which distributes oxygen to body tissues, and carries waste carbon dioxide back to the lungs. RBCs are transfused in case of trauma cases, surgery or to treat severe anemia.<br><br>

<strong>Platelets</strong> are crucial in helping blood to clot: they do this by clumping together to stop bleeding after an injury.<br><br>

<strong>Plasma</strong> is the fluid that carries all blood cells and components. Plasma contains a large number of proteins and substances which are often important ingredients in medical procedures. Plasma is transfused to patients to treat shock due to plasma loss from burns or massive bleeding.<br><br>


<strong>Plasma</strong> includes:<br><br>

Albumin - a protein useful for treating kidney and liver disease<br>
Clotting factors - used to treat types of haemophilia and diseases where blood doesn't clot properly<br>
Immunoglobins - these antibodies help protect against infections<br>

<h2>Storage</h2><br>
<img src="http://nbtc.naco.gov.in/images/storage.png"><br>

<strong>Issuing of Blood components</strong><br><br>

On request generated by authorized medical personnel your blood components will be issued to a recipient subject to blood group compatibility and blood bank inventory protocols.

</body>
</html>
</php>